### ISSUE TITLE
File uploads are processing forever

### ISSUE THREAD

**Issue by mrh-is** [contentful/contentful-management.rb#104]
I'm uploading files via the Management API, but they're never done processing. I'm trying to add secondary locales to existing files. My code works for the entries, so I think I have all the locale stuff working correctly. I can `update` with the new `file`, which is a `Contentful:Management::File` with its `contentType`, `fileName`, and `upload` set to the MIME type, file name with extension, and publicly available URL of the file, respectively. Looks like what [the API wants](http://docs.contentfulcma.apiary.io/#reference/assets/asset/create/update-an-asset?console=1).

I have verified that I can paste the URL into the file picker UI and have it work. But when I use the API (via this library), the file is stuck in processing forever (or at least longer than 10 minutes, when it takes less than a second via the file picker). The asset title, file name, and file type appear correctly in the web UI. Any thoughts?

Code boils down to this:

```ruby
Contentful::Management::File.new.tap do |file|
    file.properties[:contentType] = 'image/png'
    file.properties[:fileName] = 'cool-picture.png'
    file.properties[:upload] = 'https://example.com/cool-picture.png'
end
```

I can confirm that everything is set before using `update` on the parent asset.

I'm on v0.7.3.

**Comment by dlitvakb** [comment]
Hey @mrh-is,

Are you calling process on the asset?

The best way to do it, is like `contentful-bootstrap` deals with assets: https://github.com/contentful/contentful-bootstrap.rb/blob/master/lib/contentful/bootstrap/templates/base.rb#L108RL124

Hope this helps

Cheers

**Comment by mrh-is** [comment]
Hmm, I'll try that, thanks for the pointer. I was trying to use `asset.process`, but it said that the asset had already been processed, because the primary locale was already processed & published. I will post here after trying again.

**Comment by dlitvakb** [comment]
Hey @mrh-is,

How did it go?

**Comment by mrh-is** [comment]
Didn't work. 😞 Contentful still says the asset has already been processed.

More specific code:

```ruby
image_asset = space.assets.find(asset_id) # this works, gets the right asset
image_asset.locale = locale # change to the locale I want to add data for
localized_image = Contentful::Management::File.new.tap do |file|
  file.properties[:contentType] = file_type(existing_file_url) # this gets the MIME type, correctly set to 'image/png' for the test file
  file.properties[:fileName] = File.basename(existing_file_url)
  file.properties[:upload] = existing_file_url # this is a valid, publicly accessible URL
end
image_asset.update(title: File.basename(existing_file_url,'.*'), file: localized_image)
begin
  image_asset.process_file
rescue Exception => e
  puts e # "File has already been processed."
end
```

Like I said above, the title makes it to Contentful, and it says the file is processing (even if I don't call `process_file`). The processing just goes on forever.

Working with gem v0.7.3.

**Comment by dlitvakb** [comment]
I see what the problem is, `Asset#process_file` runs processing for each locale.

What you can do for processing a single locale is run the following:

```ruby
Contentful::Management::Request.new(
  "/#{space.id}/assets/#{asset.id}/files/#{locale}/process",
  {},
  nil,
  version: asset.sys[:version]
)
request.put
```

That will process the asset only for the specified locale.

Hope that helps

Cheers

**Comment by mrh-is** [comment]
Yay, that works! 👏 Thanks for the help!

**Comment by dlitvakb** [comment]
No problem!

Glad it helped!

**Comment by sebbean** [comment]
@dlitvakb doesnt this mean that any asset with a single locale cannot be processed?

**Comment by dlitvakb** [comment]
Hey @sebbean,

If your asset has only a single locale, it will run only for that locale. This issue was related to having some locales already processed and some not, therefore when it was hitting an already processed locale it was throwing an error, therefore requiring to manually process a single specified.

Hope that explains it better.

Cheers

**Comment by eric-gymondo** [comment]
@dlitvakb I did exactly the workaround you suggested but now I get

> Message: Validation error
Details: {
  "sys": {
    "type": "Error",
    "id": "ValidationFailed"
  },
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "required",
        "path": [
          "fields",
          "file",
          "zzz-AC"
        ],
        "details": "No file specified for locale: zzz-AC"
      }
    ]
  },
  "requestId": "250b628073bd874f01b0454e0a925a39"
}
Uncaught exception: HTTP status code: 422 Unprocessable Entity
Message: Validation error
Details: 
	* Name: required - Path: '["fields", "file", "zzz-AC"]' - Value: ''
Request ID: 250b628073bd874f01b0454e0a925a39
	/Users/eric.santos/Github/contentful-management.rb/lib/contentful/management/client.rb:388:in `execute_request'
	/Users/eric.santos/Github/contentful-management.rb/lib/contentful/management/client.rb:459:in `put'
	/Users/eric.santos/Github/contentful-management.rb/lib/contentful/management/request.rb:51:in `put'
	/Users/eric.santos/Github/contentful-management.rb/lib/contentful/management/asset.rb:63:in `block in process_file'
	/Users/eric.santos/Github/contentful-management.rb/lib/contentful/management/asset.rb:53:in `each'
	/Users/eric.santos/Github/contentful-management.rb/lib/contentful/management/asset.rb:53:in `process_file'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/templates/base.rb:129:in `rescue in block in create_assets'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/templates/base.rb:112:in `block in create_assets'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/templates/base.rb:111:in `each'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/templates/base.rb:111:in `create_assets'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/templates/base.rb:20:in `run'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/commands/update_space.rb:54:in `update_json_template'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/commands/update_space.rb:32:in `run'
	/Users/eric.santos/Github/contentful-bootstrap.rb/lib/contentful/bootstrap/command_runner.rb:23:in `update_space'
	/Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:60:in `bootstrap_update_space!'
	/Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:80:in `update_space!'
	/Users/eric.santos/Github/contentful-database-importer.rb/test.rb:56:in `<top (required)>'

Process finished with exit code 1

Could you please provide at least a hint about this? I see so many issues regarding assets and locale issues in this project without an answer I wonder if this project still active in the end.

**Comment by dlitvakb** [comment]
Hey @eric-gymondo,

Looks like your issue is different. Seems like you have a locale configured as required and non optionally blank. Therefore it's requiring you to have that locale available when publishing.

In your case `zzz-AC`.

Please check that you have content for that locale and try again.

Cheers

**Comment by eric-gymondo** [comment]
Hello @dlitvakb thanks I will check that for sure.

**Comment by eric-gymondo** [comment]
@dlitvakb I tried to mark `Allow empty fields for this locale` but when I'm trying to create the asset for the locale I still get exactly the same error, where can disable 'locale configured as required and non optionally blank' for an asset?
