### ISSUE TITLE
Erroneously reporting 'Service Unavailable, contenful.com API seems to be down'

### ISSUE THREAD

**Issue by qbunt** [contentful/contentful-management.rb#106]
Using the following code:

```
require 'contentful/management'

TOKEN_FILE_PATH = "./data/.oauth.token"
SPACE_ID = "pzben22qc4sf"

def get_access_token
  # check for the existence of the /data/.oauth.token file
  if File.exists? TOKEN_FILE_PATH
    open(TOKEN_FILE_PATH).read
  else
    raise "Please authenticate the application before using this tool"
  end
end

puts "ACCESS TOKEN: #{get_access_token}"
puts "SPACE_ID: #{SPACE_ID}"

client = Contentful::Management::Client.new(get_access_token)
puts client
space = client.spaces.find(SPACE_ID)
puts space
space.assets.all
```

We get the following output:

```
#<Contentful::Management::Client:0x007fc192162500>
Service Unavailable, contenful.com API seems to be down
test.rb:22:in `<main>': undefined method `assets' for #<Contentful::Management::ServiceUnavailable:0x007fc1921a8960> (NoMethodError)
```

Using the same space, same accessToken in Node, everything runs fine and nothing reports as a 503 (because everything is operational and online).

This recently just caused us a couple of days of issues because we assumed that the bridge was down, and it clearly isn't.

Looking at the code, it looks like maybe there's a condition that's not getting handled or getting mapped to an error hash that isn't entirely right.

**Comment by dlitvakb** [comment]
Hey @qbunt,

What happens when you use the token directly?

If it works, could you check that the path you're using is correct and that the file is properly being read? I'd recommend not using relative paths and using `File.join(File.dirname(__FILE__), 'data', '.oauth.token')` to get the proper path from the current working file.

Please let me know if that helps

Cheers

**Comment by kuma-giyomu** [comment]
Using the token directly gives the same result. The file exists and is read properly. The content can be output without any issue. Regardless, the error reported is a 503 which supposedly comes from the server.

**Comment by dlitvakb** [comment]
Hey @kuma-giyomu,

Could you open up a support ticket?

This doesn't seem to be an SDK issue

Cheers

**Comment by qbunt** [comment]
Actually, this is most definitely an SDK error. The Node SDKs and HTTP APIs
return good responses with the same token data. I initially opened a
support ticket and quickly closed it as this issue is not caused by the
platform.

**Comment by dlitvakb** [comment]
Could you then open a support ticket regarding the SDK and ask for me?

I will need your token and space ID, and this is not the place to share private tokens.

Cheers

**Comment by qbunt** [comment]
I'll do that right now, thanks @dlitvakb

**Comment by qbunt** [comment]
@dlitvakb Asked for you as requested in ticket #8997 in your support system. Please let me know when you get a chance to review. Thanks!

**Comment by dlitvakb** [comment]
Hey @qbunt,

Just replied, closing this ticket and continuing conversation over there

Cheers
