### ISSUE TITLE
Getting snapshots?

### ISSUE THREAD

**Issue by alvindu-pw** [contentful/contentful-management.rb#111]
The developers api supports getting all the snapshots of an entry or getting a snapshot by ID, wondering if this is something that can be included in the management client as well?

**Comment by dlitvakb** [comment]
Hey @alvindu-pw,

This is currently planned, we're going to add it within the next month most likely.

Cheers

**Comment by alvindu-pw** [comment]
Very cool! One nice to have is..  So right now, through the REST api we can only get snapshots by snapshot ID or pull all of it. This is not great because when we fetch an entry we only get the revision or published version. So it would great to either add snapshot id into the entry data, or give use the ability to get snapshot via version number. It's a real hassle having to pull all snapshots and search for the specific entry we want.

**Comment by dlitvakb** [comment]
Hey @alvindu-pw, I'll send this feedback to our PM team.

Thanks

**Comment by dlitvakb** [comment]
Hey @alvindu-pw,

Snapshots API has been added to the SDK, it will be released (also including Upload API), sometime between tomorrow and Monday.

Cheers

**Comment by alvindu-pw** [comment]
Really cool! Thanks a lot!
