### ISSUE TITLE
No errors for locale validation

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful-management.rb#142]
I'm using Contentful Model gem but thought I'd raise the issue here as it seems more to do with Management.

Tried doing this in `seeds.rb`:
```ruby
Root::Model::Index::Jumbotron::CallbackForm.create({
  :title_text => "Get Your Free Quote",
  :footer_text => "and we'll call to tell you\n\ncall us on 123 123 123 to get a quote now",
  :button_text => "Get a callback"
})
```
And got the following error:
```
Contentful::Management::UnprocessableEntity: HTTP status code: 422 Unprocessable Entity
Message: Validation error
Details:
	* Name:  - Path: '' - Value: ''
	* Name:  - Path: '' - Value: ''
	* Name:  - Path: '' - Value: ''
```
Not sure how to interpret the error.

**Comment by nomasprime** [comment]
Now I'm not sure: maybe it's Contentful Model.

**Comment by dlitvakb** [comment]
Can you share the `ex.response.raw` content?

Looks like it may be an edge case on the error reporting that's causing the error not to display.

Also, regarding the creation error itself, check if your field IDs match the values you're sending as keys.

The SDK does snake_case/camelCase automatic conversions when populating the objects or saving from an already existing object, but it doesn't know what to do when using `ContentType::create` as it's a direct call to the API that's not going through the content type resolver.

Let me know if that helps,

Cheers

**Comment by nomasprime** [comment]
Oh, from an exception? I'll check.

**Comment by nomasprime** [comment]
Changed `ContentfulModel::Manageable::ClassMethods#create` to:
```ruby
def create(values = {}, publish = false)
  begin
    entry = management.entries.create(
      management.content_types.find(
        ContentfulModel.configuration.space,
        content_type_id
      ),
      values
    )
  rescue StandardError => e
    puts e.response.raw
  end

  if publish
    entry.publish
    entry = self.find(entry.id)
  end

  entry
end
```
Which gave me:
```
{
  "sys": {
    "type": "Error",
    "id": "ValidationFailed"
  },
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "message": "Invalid field locale code \"en-UK\", has to be one of \"en-GB\"",
        "details": "The property \"en-UK\" is not allowed here."
      }
    ]
  },
  "requestId": "0b0efec33b24d08834e89ad1f1de8964"
}
```
Should be pretty straightforward from here. Wanted to leave breadcrumbs here for myself and others 🙂

**Comment by dlitvakb** [comment]
Hey @nomasprime,

Looks like your default locale does not match your space locale.

I'll also add this edge case error to the CMA SDK error handling.

Cheers

**Comment by nomasprime** [comment]
Confirmed @dlitvakb, updated locale and works as expected.

I've changed the title of the issue accordingly.

**Comment by dlitvakb** [comment]
Thanks @nomasprime!

I'll try to get this fixed and released within this week.

Cheers
