### ISSUE TITLE
Pagination on assets doesn't work without first calling limit

### ISSUE THREAD

**Issue by Soliah** [contentful/contentful-management.rb#143]
If I do

```ruby
client = Contentful::Management::Client.new(ENV['CONTENTFUL_MANAGEMENT_ACCESS_TOKEN'], logger: Rails.logger, log_level: Logger::DEBUG, max_rate_limit_wait: 10)
space = client.spaces.find(ENV['CONTENTFUL_SPACE_ID'])
assets = space.assets.all
assets = assets.next_page
```

The query hash on the request isn't instantiated:

```
NoMethodError: undefined method `[]=' for nil:NilClass
from /Users/cchow/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/contentful-management-1.10.0/lib/contentful/management/array.rb:27:in `next_page'
```

Calling `space.assets.all(limit: 100)` works with `next_page` though.

This doesn't seem to affect entries (don't need to call `limit` first).

**Comment by dlitvakb** [comment]
Hey @Soliah,

Just found the issue, I'll fix it and create a PR today.

Cheers

**Comment by dlitvakb** [comment]
This has just been merged, I'll look into any other pending open tickets, and make a release hopefully today, otherwise tomorrow.

Cheers
