### ISSUE TITLE
Possible to resolve users from snapshots?

### ISSUE THREAD

**Issue by raybradley** [contentful/contentful-management.rb#146]
For a given Entry I'd like to enumerate all snapshots and display the name of the person who made the change as well as the timestamp. I can get the timestamp easily enough, but users show up as #<Contentful::Management::Link: @sys={:type=>"Link", :linkType=>"User", :id=>"23hkj6hkjs809sd"}>

It's not clear from the docs if there's a way to fetch or inflate that user. Ideas?

**Comment by dlitvakb** [comment]
Hey @raybradley,

This is not possible, only user that you are only to fetch information from is the user associated with your own token.

If you need more information please contact [support](https://support.contentful.com).

Cheers
