### ISSUE TITLE
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful-management.rb#152]
Occasionally, the management gem crashes on request to Contentful with this error. It's not readily reproducible, and happens during our content import process, so this is blocking us from fully moving to Contentful for our content solution.

Information online is hard to find, but some indicate this may be due to a misconfiguration on Contentful's servers, which would make sense if only a few of the CMA servers have the misconfiguration (since the problem is not consistent). 

Any guidance?

```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello
project-gemset/gems/http-2.2.2/lib/http/timeout/null.rb:26:in `connect'
project-gemset/gems/http-2.2.2/lib/http/timeout/null.rb:26:in `connect_ssl'
project-gemset/gems/http-2.2.2/lib/http/timeout/null.rb:35:in `start_tls'
project-gemset/gems/http-2.2.2/lib/http/connection.rb:158:in `start_tls'
project-gemset/gems/http-2.2.2/lib/http/connection.rb:44:in `initialize'
project-gemset/gems/http-2.2.2/lib/http/client.rb:60:in `new'
project-gemset/gems/http-2.2.2/lib/http/client.rb:60:in `perform'
project-gemset/gems/http-2.2.2/lib/http/client.rb:41:in `request'
project-gemset/gems/http-2.2.2/lib/http/chainable.rb:19:in `get'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/client.rb:453:in `public_send'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/client.rb:453:in `http_send'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/client.rb:399:in `block in get'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/client.rb:343:in `execute_request'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/client.rb:398:in `get'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/request.rb:41:in `get'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/resource_requester.rb:69:in `get'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/resource_requester.rb:15:in `all'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/resource.rb:186:in `all'
project-gemset/gems/contentful-management-1.10.1/lib/contentful/management/content_type_entry_methods_factory.rb:26:in `all'
(our code has control below here)
```

**Comment by rezonant** [comment]
Oh, I should've added a backtrace. Also, this is Ruby 2.4.0 on Mac OS X Sierra

**Comment by rezonant** [comment]
I've also opened a related support request at Contentful

**Comment by rezonant** [comment]
Was using OpenSSL 1.1.0f, upgraded to 1.1.0h but the issue persists:
```
$ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.1.0h  27 Mar 2018
```
Also configured OpenSSL to use TLS with an initializer:
```
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version] = 'TLSv1_2'
```
This also has no effect wrt this error.

**Comment by rezonant** [comment]
Don't know for sure yet, but possibly setting OpenSSL to only ever try TLS v1.2 and disabling compression may be fixing this issue for me:

```
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:options] |= OpenSSL::SSL::OP_NO_COMPRESSION
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ciphers] = "TLSv1.2:!aNULL:!eNULL"
```

**Comment by dlitvakb** [comment]
Hi @rezonant,

I'll add our security and infra engineers as they may understand more of this issue to the conversation. I'm not sure of what could be happening. And it seems not to be an specific issue of the SDK but rather of the SSL handshake.

cc @felipecoe @elblivion

**Comment by qumberali22** [comment]
@dlitvakb I'm facing the same issue could please tell me how you solve this.

**Comment by dlitvakb** [comment]
Hey @qumberali22,

Please follow the guide linked here: https://guides.rubygems.org/ssl-certificate-update/ It will explain better how to fix this.

Cheers

**Comment by thanhltx** [comment]
I've had same issue.

It was successfully when I tried 
`ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'`
or 
but I was not successfully for the url that I would like to get: and the error was
SSL_connect returned=6 errno=0 state=SSLv3/TLS write client hello (OpenSSL::SSL::SSLError)'

It was successful when I try this url with curl connection as below:
```
curl --location --request GET '<url>' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic <token>' \
--data-raw ''
```

I'm not sure what did I miss settings or configuration in my ruby

Thanks for any help or suggestion

**Comment by thanhltx** [comment]
I knew what is the problem.

That because default ssl_version is something which is used one in Api endpoints.
To check what is the ssl_version is used: [https://gist.github.com/mlsaito/1b149f7fd4e070c40465913f8c89a2c5](https://gist.github.com/mlsaito/1b149f7fd4e070c40465913f8c89a2c5).

below is example in httparty, that can fix this issue
HTTParty.get(
            url,
            headers: headers,
            query: request_query,
            ssl_version: :TLSv1_2
          )
