### ISSUE TITLE
API errors are returned instead of thrown

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful-management.rb#156]
```ruby
    @client = Contentful::Management::Client.new(...)
    @space = @client.spaces.find(@space_id)
    puts @space.class
    # --> ::Contentful::Management::RateLimitExceeded
```
**Expected behavior:**
Errors should always be thrown, never returned.

**Actual behavior:**
Upon rate limiting, `spaces.find()` is returning the error object.

This behavior stems from the ResourceBuilder (resource_builder.rb, line 75):

```ruby
      # Starts the parsing process.
      # @return [Contentful::Management::Resource, Contentful::Management::Error]
      def run
        if response.status == :ok
          create_all_resources!
        else
          response.object
        end
      end
```

**Comment by rezonant** [comment]
One workaround is a monkey patch, though it may have side effects:

```
class ::Contentful::Management::ResourceBuilder
    # Starts the parsing process.
    # @return [Contentful::Management::Resource, Contentful::Management::Error]
    def run
      if response.status == :ok
        create_all_resources!
      else
        raise response.object
      end
    end
end 
```

**Comment by dlitvakb** [comment]
Hey @rezonant,

In the client instantiation you can send `raise_errors: true` and errors will be thrown instead of returned. This default has not been changed for backwards compatibility reasons.

Cheers

**Comment by drewmoore** [comment]
Could this be included in a future release? I would argue that this should be the default behaviour. We are running rake tasks that affect thousands of entries. We had not realised that many updates were failing silently.

**Comment by dlitvakb** [comment]
Hey @drewmoore,

Not for the moment, given that it would require a major version change.

Please consider updating your client instantiation code to include the `raise_errors: true`.

Cheers
