### ISSUE TITLE
409 Conflict while creating a new asset

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful-management.rb#158]
Hello, for some reason I am receiving a 409 Conflict when I go to publish an asset that the script itself is creating. There is no human modifying the record, and this code was working perfectly until yesterday. 

I am using the Contentful Management gem for Ruby (raw, without Contentful Model) to do this. Code:

```
  def create_image_asset(url, title: nil, description: nil)
    return nil unless url 

    # Create an asset for the image 
    cf_image = Contentful::Management::File.new 
    content_type = if url.end_with?('.png')
      'image/png' 
    elsif url.end_with?('.jpg')
      'image/jpeg'
    else 
      nil 
    end 

    raise "Could not determine image format for URL '#{url}'" unless content_type

    filename = url.gsub(/^.*\//, '')
    cf_image.properties[:contentType] = content_type 
    cf_image.properties[:fileName] = filename
    cf_image.properties[:upload] = url

    title = filename unless title 
    description = "Imported by Platform from '#{url}'" unless description 

    asset = @space.assets.create(title: title, description: description, file: cf_image)

    if asset.kind_of?(Contentful::Management::ServerError) 
      raise "Received error while publishing image to Contentful: #{e.inspect}"
    end 

    asset.process_file 
    begin 
      asset.publish
    rescue StandardError => e
      Rails.logger.error "Failed to publish image asset. Asset had description '#{description}', title '#{title}', filename '#{filename}'"
      asset = nil
    end

    return asset
  end 
```

Why would this result in a 409 Conflict? Does @space.assets.create() return an existing object in some case? I used to re-raise after logging the failure, but this is running an ongoing content importer into Contentful and we're reliant on that content being imported into Contentful on a timely basis. For now our editors are going to have to manually find the thumbnail for the content, but we'd like to not have to do that. I have also filed a support request with the Contentful support team.

**Comment by dlitvakb** [comment]
Hey @rezonant,

Hey @rezonant,

The issue happening here, is that some times, the processing takes a bit longer (it is an async process), therefore I'd say you should wait a little bit before publishing, this is the way I solve it in the bootstrap tool: https://github.com/contentful/contentful-bootstrap.rb/blob/master/lib/contentful/bootstrap/templates/base.rb#L133-L146

Hope this helps,

Cheers

**Comment by mrclay** [comment]
I found something more reliable: Re-request the asset in a loop until the `url` property is added to the `file` field. Then publish should succeed first try.

If your local asset copy lacks the `url`, publish is going to keep failing.
