### ISSUE TITLE
.total method negates skip and limit, bug or feature? (2.3.0)

### ISSUE THREAD

**Issue by a-lehdet** [contentful/contentful-management.rb#174]
Hi,

I noticed something peculiar with how `.total` method works when combined with `skip` and `limit` parameters.

This is how the client has been initialized in my code:

```
require "contentful/management"

client = Contentful::Management::Client.new("<TOKEN>")
space = client.spaces.find("<SPACE-ID>")
environment = client.environments("<SPACE-ID>").find("master")
```
There is a total number of 5327 entries of the content type "article" in my space.

```
environment.entries.all(content_type: "article").total
>> 5327
```

When I apply `skip` and/or `limit` parameters, the returned number still remains the same.

```
environment.entries.all(content_type: "article", limit: 100, skip: 100).total
>> 5327
```

However, when I use the `"sys.id[match]"` filter, the total amount is affected.

```
environment.entries.all(content_type: "article", "sys.id[match]" => "XYZ123").total
>> DIFFERENT AMOUNT
```

Is this a working as intended, or is it a bug?

**Comment by dlitvakb** [comment]
Hey @a-lehdet,

`total` is the amount of entries that match the query, not the amount of entries in the current request. You can use it to paginate.

If you want to know the amount of entries in the current query results, then you should use `#size`.

Cheers

**Comment by a-lehdet** [comment]
Hi @dlitvakb

OK, that makes sense. I already tried using `size` which works...up to a point. The problem is, when the limit is set high enough, the response payload grows too big (?) and causes an error

For example, in our case the a limit of 100 works...

```
environment.entries.all(content_type: "article", limit: 100).size
=> 100
```

...but a limit of 300 doesn't work.

```
environment.entries.all(content_type: "article", limit: 300).size
Traceback (most recent call last):
        2: from /Users/ttam/.rvm/rubies/ruby-2.5.1/bin/irb:11:in `<main>'
        1: from (irb):43
NoMethodError (undefined method `size' for #<Contentful::Management::BadRequest:0x00007fafc58f7d30>)
```

**Comment by dlitvakb** [comment]
Hey @a-lehdet,

There's 2 different things happening here:

1. As you're not using `raise_errors: true` instead of having an exception thrown, you're getting the error back from the API, then calling `#size` on an error, of course returns an error, because you don't have the expected object there.
2. The error you're receiving is most likely because you exceeded the maximum response size limit (which is 7MB), therefore receiving an error.

Hope this helps,

Cheers

**Comment by a-lehdet** [comment]
@dlitvakb 

Confirmed; I turned on `raise_errors` and the response is indeed too big as suspected.

```
environment.entries.all(content_type: "article", limit: 300).size
Traceback (most recent call last):
...
Contentful::Management::BadRequest (HTTP status code: 400 Bad Request)
Message: Response size too big, was: 8237697b. Maximum allowed response size: 7340032b.
```

**Comment by dlitvakb** [comment]
Hey @a-lehdet,

Glad to be of help,

Cheers
