### ISSUE TITLE
Updating field properties not working !?

### ISSUE THREAD

**Issue by twei55** [contentful/contentful-management.rb#182]
I am using this line from the README to update my content type:

```
blog_post_content_type.update(name: 'Post', description: 'Post Description', fields: [title_field])
```

I read content_type definitions from a JSON file and update my content model, but as far as I can see, there is no change applied to fields that already exist. I can add additional fields but I can't change properties of already existing fields.

This is the code I use to update the content type:

```
def update_content_type(content_type, json)
  content_type.update(
    name: json['name'],
    description: json['description'],
    fields: create_fields(json['fields']),
    displayField: json['displayField']
  )
end

def create_fields(json_fields)
  fields = []
  json_fields.keys.each do |key|
    fields.push(create_field(json_fields[key]))
  end

  fields
end

def create_field(json_field)
  new_field = Contentful::Management::Field.new
  new_field.id = json_field['id']
  new_field.name = json_field['name']
  new_field.type = json_field['apiType']
  new_field.disabled = json_field['disabled'] == "true" ? true : false

  if json_field['linkType']
    new_field.link_type = json_field['linkType']
  end

  if json_field['items']
    new_field.items = create_items(json_field['items'])
  end

  new_field
end
```

**Comment by dlitvakb** [comment]
Hey @twei55,

Everything looks fine,

I'd try to change the `#update` call to use `#save` instead like follows and see if it works:

```ruby
content_type.tap do |ct|
  ct.name = json['name']
  ct.description = json['description']
  ct.fields = create_fields(json['fields'])
  ct.display_field = json['displayField']
end.save
```

Please let me know if this doesn't work, and we can follow up from there, as if it doesn't I'd need specific information about the JSON content you're trying to use and possibly your space.

Cheers

**Comment by twei55** [comment]
Hey @dlitvakb,

thanks for your reply. I tried your suggestion but it doesn't work for me, so I am not able to update my content types using either update or save. Not absolutely sure but I guess this has nothing to do with my JSON data because I create the content_types with the same data w/o any problems. How can we proceed? How can I send you the information about my space? Thanks in advance

**Comment by dlitvakb** [comment]
Hey @twei55,

You can create a support ticket at https://support.contentful.com and request for my help, we can discuss there in more depth.

Cheers

**Comment by twei55** [comment]
@dlitvakb I solved the issue on my side. It seems that there are certain limitations (which make sense), so changing the id of an already existing field is not possible as well as removing a field or changing the type. Nevertheless it is possible to change the name of a field, adding additional fields or changing meta properties (disabled, required, ...).
