### ISSUE TITLE
Field named `id` assumes it is the system `id` value

### ISSUE THREAD

**Issue by seancdavis** [contentful/contentful-management.rb#185]
When there is a field named `id` for an entry and I attempt to save the entry, it conflicts with the Contentful ID. Thus, I am unable to update an entry unless the custom `id` field matches the system's `id` value.

Suppose `client` is defined as a Contentful environment object, and I retrieve an entry from the database:

```rb
id = "3GBVdrGOcg4ek2UQYSeywk"
entry = contentful.entries.find(id) # => <Contentful::Management::Entry>
```

Now suppose that entry has a field defined in its content model called `id` and it's set to `123`:

```rb
entry.id # => 123
```

So if I try to update another field, say `title`, and then save the entry again, it will create a new entry rather than saving the new entry:

```rb
entry.title = "My New Title"
entry.save # => creates a new entry with `id` 123
```

Knowing that choosing `id` as a custom field name is not a great decision, it is possible to take this approach through the API , and seems like the gem would benefit from keeping an entry's fields separate from its system data.

**Comment by dlitvakb** [comment]
Hey @seancdavis,

You can still set the value for the field called `id`, without affecting the `sys.id`.

To do so, you need not to use the short-hand accessor, but instead use the more verbous way of:

```ruby
entry.fields(:en-US)['id'] # for reading - you may omit the locale if it matches your client's default locale

entry.fields(:en-US)['id'] = 123 # for writing
```

This will avoid using the short-hand accessor, and allow you to use the field.

This behaviour will not be changed since the short-hand accessor is a convenience method.

Hope this explains it a little better and helps you solve your issues.

Cheers

**Comment by dlitvakb** [comment]
One caveat, the field may be have to be called using a symbol instead of a string. I'm on mobile currently without access to a laptop to check.

Cheers

**Comment by seancdavis** [comment]
Thanks for the quick response, @dlitvakb! That did the trick.

**Comment by sanczi789** [comment]
I'm having a similar issue, when creating an entry with field `id` it creates but set t he Contentful entry id to that value as well. I tried with:
 x_content_type.entries.create(id: 123, name: 'name') 
and 
entry = x_content_type.entries.new 
entry.name = 'name'
entry.fields('en-US')[:id} = 123
entry.save

And when I try creating it first and then updating id it creates it again
