### ISSUE TITLE
Can't find user with user_id

### ISSUE THREAD

**Issue by andre8888** [contentful/contentful-management.rb#188]
ContentfulWriteClient = Contentful::Management::Client.new(
  Rails.application.secrets.contentful_management_access_token
)

This is working: ContentfulWriteClient.users.find('me')
=> #<Contentful::Management::User: @properties={:email=>"xxx", :lastName=>"xxx", :firstName=>"xxx", :avatarUrl=>"xxx", :activated=>true, :confirmed=>true, :signInCount=>7} @sys={:type=>"User", :id=>"2XfpR7Cg0XF9mpl0zw8g08", :version=>15, :createdAt=>Tue, 07 Aug 2018 22:44:34 +0000, :updatedAt=>Mon, 18 Mar 2019 16:36:53 +0000}>

But this is not working: ContentfulWriteClient.users.find('2XfpR7Cg0XF9mpl0zw8g08')
=> #<Contentful::Management::NotFound: HTTP status code: 404 Not Found
Message: The path you tried to reach is unknown or doesn't support this HTTP method.

**Comment by vitscurtu** [comment]
Hi, I have the same issue. Any plans on addressing it and if not, is there a workaround?

Thanks,
Vitalie

**Comment by dlitvakb** [comment]
Hey @andre8888 and @vitscurtu,

We're adding the User Management API soon to this SDK.

Cheers
