### ISSUE TITLE
Is there a way to find the entry with slug?

### ISSUE THREAD

**Issue by antwonlee** [contentful/contentful-management.rb#191]
Is there a way to query through slug opposed to id?  I am doing something simple like this in Rails: 

```ruby
def index
    render locals: {
      updates: contentful.entries(
        content_type: 'myUpdates', 
        include: 10,
        order: '-fields.scheduledDate',
      )
    }
end

def show
  update = contentful.entry(params[:id])
end

# https://myapp.com/updates/this-is-slug-name-in-contentful
```

**Comment by dlitvakb** [comment]
Hey @antwonlee,

You can do that by doing a check on that particular field. It would look something like `contentful.entries(content_type: 'myUpdates', include: 10, 'fields.slug' => params[:id]).first`.

Hope this helps,

Cheers

**Comment by dlitvakb** [comment]
Also, this is a question better suited for our CDA SDK repo: https://github.com/contentful/contentful.rb

**Comment by antwonlee** [comment]
Thanks, @dlitvakb! I found that official ruby library after I posted the question here.  That helps!
