### ISSUE TITLE
Difficulty with Rich Text Block

### ISSUE THREAD

**Issue by malorie16** [contentful/contentful-management.rb#198]
I might be missing something but is there an addition step needed to push content up to a rich text field? I'm currently trying to push markup to a rich text field but it's breaking here: 

![Screen Shot 2019-06-21 at 12 02 44](https://user-images.githubusercontent.com/37854050/59935768-8b629680-941c-11e9-8422-338913bd13fa.png)

Here's my code: 

![Screen Shot 2019-06-21 at 12 04 44](https://user-images.githubusercontent.com/37854050/59935913-ccf34180-941c-11e9-8eae-40fe601d9c26.png)

**Comment by dlitvakb** [comment]
Hey @malorie16,

You haven't included the error itself, so I cannot understand what may be going on.

Please include the exception message so I can look further into this.

Cheers

**Comment by malorie16** [comment]
Hi! Thanks for your quick response. Here's a screenshot of the error:

![Screen Shot 2019-06-21 at 13 47 12](https://user-images.githubusercontent.com/37854050/59941435-2febd500-942b-11e9-8794-52cbd8995905.png)

**Comment by dlitvakb** [comment]
Hey @malorie16,

Looks like you're trying to input Markdown into a Rich Text field, and that's what's failing. But I cannot confirm that without knowing what your `content` field actually is or what validations it does have if it is not actually RichText.

Cheers

**Comment by malorie16** [comment]
Hi! That's correct - I need to add markdown. So is the only way to add markdown into a rich text field to convert it using the `rich-text-from-markdown` package? As seen in this article: https://www.contentful.com/developers/docs/tutorials/general/migrate-to-rich-text/#10-markdown-migration-script

**Comment by dlitvakb** [comment]
Hey @malorie16,

Yes, either using our JS lib to convert it to Rich Text JSON, or doing it manually.
The other possibility, is just using a regular Long Text field, if you just need Markdown and not any of the additional features that RichText provides.

Cheers

**Comment by malorie16** [comment]
Yea we need to be able to embed components into these fields so it absolutely needs to be a Rich Text field. Curious - how exactly would I got about doing it manually? When making my POST request I tried to format the content using a Rich Text field response as a template with no luck. Push comes to shove, it seems this will be my option: https://www.contentful.com/developers/docs/tutorials/general/migrate-to-rich-text/#10-markdown-migration-script

**Comment by dlitvakb** [comment]
Hey @malorie16,

That example uses [this library](https://github.com/contentful/rich-text/blob/master/packages/rich-text-from-markdown/src/index.ts) to do the conversion, you could replicate this logic in Ruby if you need it to be exclusively in Ruby.

Otherwise, you could write a small intermediate script that passes your markdown through that library, and then you consume it from your Ruby script.

Cheers

**Comment by malorie16** [comment]
Gotcha. Thanks so much for your help!
