### ISSUE TITLE
Creating entry with field 'id' doesn't work

### ISSUE THREAD

**Issue by sanczi789** [contentful/contentful-management.rb#223]
I've got a content type with field 'id', whn I'm trying to create it using the gem with:
entry = entry_content_type.entries.create(id: 123, name: 'Name') I get:
`Message: Validation error
Details: 
        * Name:  - Path: '' - Value: ''
        * Name:  - Path: '' - Value: ''`

**Comment by rubydog** [comment]
Hi @sanczi789, thanks for reporting the issue. Which version of sdk are you using?

**Comment by sanczi789** [comment]
not sure? I'm using contentful-management gem 3.0.0, can it be sth with locales? my space has a default locale other than 'en-US' but when using the gem it still seems to think that's the default one.

**Comment by rubydog** [comment]
Hi @sanczi789, I am glad you found solution. Can you also please share your findings with the community?

Cheers

**Comment by sanczi789** [comment]
I had to set the default locale here:
client = Contentful::Management::Client.new('ABC123', default_locale: 'def-locale')
