### ISSUE TITLE
Get all users implementation missing

### ISSUE THREAD

**Issue by ghepting** [contentful/contentful-management.rb#224]
Hey, it looks like contentful-management.rb is missing the get all users API feature, which is quite critical for some user access control synchronization work our team at Square is about to execute on

API Reference: https://www.contentful.com/developers/docs/references/user-management-api/#/reference/users

Ruby SDK missing `.all` method/functionality: 
![image](https://user-images.githubusercontent.com/492573/117469938-41a5cb00-af24-11eb-9d4b-7fb7963df5d2.png)

Any ETA on this missing functionality being added?

**Comment by rubydog** [comment]
@ghepting I am working on it, I will keep you posted.

**Comment by ghepting** [comment]
Fantastic! Thanks for the update :)

**Comment by ghepting** [comment]
Hey @rubydog – curious, is your scope of work on this encapsulating all of the User Management API functionality?

**Comment by rubydog** [comment]
@ghepting No, just get all users API feature.
