### ISSUE TITLE
editor_interface missing sidebar implementation

### ISSUE THREAD

**Issue by ghepting** [contentful/contentful-management.rb#229]
Hello! It appears that contentful-management.rb is missing the implementation to manage the sidebar configurations on a `Contentful::Management::EditorInterface` resource, which is critical for some of the work our team at Square is working on

Reference: https://www.contentful.com/developers/docs/extensibility/custom-sidebar/ 
API Reference: https://www.contentful.com/developers/docs/references/content-management-api/#/reference/editor-interface 

Ruby SDK missing `.sidebar` getter/setters. Upon inspection of the `raw_object` the API response is correct, but the ruby SDK is missing this piece.

Opening an enterprise support ticket referencing this github issue. In the meantime, do you recommend modifying the raw_object manually and saving, or is there a better workflow within the constraints of the current implementation?

![image](https://user-images.githubusercontent.com/492573/129217678-549fb799-8915-4bb5-9d1f-3f6c23c58f35.png)

**Comment by rubydog** [comment]
Hey @ghepting, I am taking a look at it now. I will keep you posted on my progress.

Cheers
