### ISSUE TITLE
URI.escape is obsolete and does not work with URI 0.10.1

### ISSUE THREAD

**Issue by anandpdoshi** [contentful/contentful-management.rb#251]
Contentful management client uses [URI.escape in request.rb](https://github.com/contentful/contentful-management.rb/blob/master/lib/contentful/management/request.rb#L27). However, URI.escape has been marked obsolete and upon updating URI from 0.10.0 to 0.10.1, the contentful management client stops working due to the missing escape method.

More context about URI.escape:
* https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string
* https://stackoverflow.com/questions/2824126/whats-the-difference-between-uri-escape-and-cgi-escape

Could the team implement the URI encoding using a different approach?

**Comment by rubydog** [comment]
Hey @anandpdoshi,

Thanks for spotting it. I will look into the issue.

Cheers

**Comment by ghepting** [comment]
https://github.com/contentful/contentful-management.rb/pull/252

**Comment by anandpdoshi** [comment]
@rubydog do you know when the new version of the management client will be released?
