### ISSUE TITLE
Question: Query using date comparison

### ISSUE THREAD

**Issue by fdocr** [contentful/contentful-management.rb#262]
Hi, I have a query that looks like this:

```ruby
entries = environment.entries.all("content_type" => content_type.id, 'sys.createdBy.sys.id' => user_id)
```

How could I add a filter to that query for entries created in the last 24h? Similar to how in Rails I would query ActiveRecord like `.where("created_at > ?", 1.day.ago)`, I'm just unsure how I could do that using the gem. Thanks!

**Comment by rubydog** [comment]
Hi @fdocr ,I'll look into this and get back to you with an answer by next week.

Cheers

**Comment by rubydog** [comment]
Hi @fdocr, You can achieve the desired filtering using the range operator in your query. For more details, refer to the [Contentful documentation on search parameters and ranges](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/ranges).

Here is a Ruby example demonstrating how to use range operators with the Contentful Content Management API:
```
require 'contentful/management'

client = Contentful::Management::Client.new('<content_management_api_key>')

# Less than:
entries = client.entries('sys.createdAt[lt]' => '2013-08-28')

# Less than or equals:
entries = client.entries('sys.createdAt[le]' => '2013-08-28')

# Greater than:
entries = client.entries('sys.createdAt[gt]' => '2013-08-28')

# Greater than or equals:
entries = client.entries('sys.createdAt[ge]' => '2013-08-28')

```

**Comment by rubydog** [comment]
Closing. Please re-open if the issue persists.
