### ISSUE TITLE
Implement :disabled property on Field class

### ISSUE THREAD

**Issue by jsdalton** [contentful/contentful-management.rb#50]
I ran into an issue trying to do `content_types.fields.destroy()` ... from what I can tell, Contentful is very unhappy when a field goes missing entirely. Although it will allow the update to proceed, future attempts to activate the content type will fail (through the admin and through the API) with the error "Error activating "Product": Previously published fields are missing or invalid". Note I emailed support@contentful.ccom with details about this.

As I looked to resolve for my own use of the API, it occurred to me that the admin itself does not support "deleting" fields, it only supports disabling them. The API also supports disabling fields with the boolean :disabled which is returned from the API as true when the field is disabled. If the flag is passed to the API it is respected.

So a feature request would be to add the property :disabled to the Field class.

Presumably an additional beneficial feature would be to either reimplement `destroy` to only disable instead of removing, or to add a separate implementation of `disable` to content_type.fields that disabled the field.

I've resorted to adding the property to Field via class_eval for my purposes and it suffices.

Thanks!

(Side note: Sorry to bug you guys with all these issues, but the implementation I'm working on is putting this API through its paces, so I'm just logging any issues or shortcomings I'm uncovering. I have one or two more issues to log in addition to this).

**Comment by pxlpnk** [comment]
Thank you for your input, keep it coming :dancers: 

There is a bit of a discrepancy between what the user interface allows you to do and what the api allows.
Basically the UI tries to prevent you from breaking stuff, the api on the other hand gives you way more and less opinionated access to content types and entries.
In general deleting a field from a content type before it is activated is ok. However the api will not (at the moment) stop you from deleting a field from an activated content type. Once a content type is activated the field should be disabled.

For the request: adding the `disable` field makes total sense, make `destroy` behave like `disable` is the wrong way to go in my opinion and the api should let you know that this is a bad idea. 
I will discuss this with the backend team and will add the `disable` feature to the roadmap for the gem.

Could you maybe share your code?

**Comment by jsdalton** [comment]
Makes sense. I actually ended up not deleting any fields, because in my use case I'm trying to delete fields on already activated content types. So ultimately, being able to explicitly disable / reenable fields is the feature that works.

First and foremost, actually adding a property that tracks the disabled status of the field is the most helpful step:

````ruby
        ::Contentful::Management::Field.class_eval do
          # Contentful Management gem doesn't keep disabled, so monkeypatch it here
          # until this gets implemented
          property :disabled, :boolean
        end
````

Doing that, disabled just becomes one more property to manage. So for example to disable a given field, I'm doing something like this:

````ruby
          # Where field_id is the ID of the field we're trying to disable
          fields = content_type.fields.map do |field|
            if field.id == field_id
              field.disabled = true
            end
            field
          end
          content_type.update(fields: fields)
````
