### ISSUE TITLE
displayField causing validation errors when not set

### ISSUE THREAD

**Issue by jsdalton** [contentful/contentful-management.rb#53]
This related to pull request #52.

So i just upgraded to 0.6.1 and in doing so I hit a validation error in the case where a display field is not defined on a content type. Digging here's what I think might be happening:

`:displayField` is a string property. When I load up a content type without a displayField being set, the nil or missing value is being coerced into a blank string i.e. `""`. On a subsequent update to that content type, the displayField is now being explicitly passed in the request as displayField: "" (that is instead of dispalyField: null). This works, but when the content type is activated a validation error is thrown:

````json
{
  "sys": {
    "type": "Error",
    "id": "ValidationFailed"
  },
  "message": "Validation error",
  "details": {
    "errors": [
      {
        "name": "referencesFieldId",
        "details": "Attribute displayField must reference a field's id",
        "displayFieldValue": "",
        "allowedValues": [
          "productName",
          "headling",
          "description",
          "bullets",
          "pdpSketch",
          "relatedContent",
          "lifestyleImages"
        ]
      }
    ]
  }
}
````

Not sure the best way to solve, but you might need to check if `display_field.blank?` and then explicitly set `:displayField` to nil if so, as opposed to letting the `""` value slip through.

We're holding off on 0.6.1 in the meantime.

Many thanks!

**Comment by pxlpnk** [comment]
See #54 for a fix
