### ISSUE TITLE
"NoMethodError: undefined method `version=' for nil:NilClass" after `Contentful::Management::Space.all`

### ISSUE THREAD

**Issue by samme** [contentful/contentful-management.rb#56]
~~~
> Contentful::Management::Space.all
NoMethodError: undefined method `version=' for nil:NilClass
	from /Library/Ruby/Gems/2.0.0/gems/contentful-management-0.6.1/lib/contentful/management/request.rb:13:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/contentful-management-0.6.1/lib/contentful/management/space.rb:29:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/contentful-management-0.6.1/lib/contentful/management/space.rb:29:in `all'
~~~

**Comment by pxlpnk** [comment]
Thank you for reporting this issue.
How are you initialising the client?
Please replace space/organization ids and your access token with placeholders in your code when posting it.

**Comment by samme** [comment]
```ruby
@manage = Contentful::Management::Client.new "[access token]"

# later:

def manage_space
  Contentful::Management::Space.find "[space id]"
end
```

I think I fixed it by moving the initialization inside the helper:

```ruby
def manage_space
  @manage ||= Contentful::Management::Client.new "[access token]", raise_errors: true
  Contentful::Management::Space.find "[space id]"
end
```

**Comment by pxlpnk** [comment]
You need to make sure that the client is initialised before the first api call.
Depending on your application you want to do this when starting the app, or lazy on the first call through a wrapper.

**Comment by samme** [comment]
Yes, I thought I'd structured it that way — I was initializing during startup and then calling the helper from an interactive console. But I guess not.

Thanks.
