### ISSUE TITLE
Using a simple field assignment does not work

### ISSUE THREAD

**Issue by neonichu** [contentful/contentful-management.rb#61]
```ruby
q = content_type.entries.new
q.name = "Hello World"
puts q.fields
# => {}
```

This should result in `fields` being set to `{:name=>"Hello World"}`.

Using `q.name_with_locales = { "en-US" => "Hello World" }` works as intended, though.

**Comment by ranakhalil** [comment]
I saw this problem with 0.7.0, however when I reverted back to 0.6.0 fields assignment worked and the field was saved and published!
