### ISSUE TITLE
Cannot update entries/assets when en-US does not exist in the space

### ISSUE THREAD

**Issue by kylethornton** [contentful/contentful-management.rb#73]
I have tried every combination that I can but it seems that the api is unable to create entries/assets properly (with localization) when en-US doesn't exist in the Space as a locale. We have en-GB and es-ES

I have a content type in the variable ```jo``` and that type has a Name ```name``` (a string) and a Value ```value``` (a json obejct) field. The Value field has localization enabled, the Name field does not.
```
new_entry = jo.entries.create(:id => 'hello-world')
```
I now have a ```new_entry``` with id ```hello-world```

Now I try to set attributes (I have tried this on the create call above to, but it doesn't work)
```
new_entry.name = "Hello World"
new_entry.locale = 'en-GB'
new_entry.value_with_locales = {'en-GB'=>{"1"=>"2"}, 'es-ES'=>{"3":"4"}}
res = new_entry.save
JSON.parse(new_entry.error[:details])['details'] #{"errors"=>[{"message"=>"Invalid field locale code \"en-US\", has to be one of \"en-GB\", \"es-ES\"", "details"=>"The property \"en-US\" is not allowed here."}]}
```

It appears that the locale is defaulting to en-US even though it isn't even active in the Space.

**Comment by dlitvakb** [comment]
Hey @kylethornton,

Thanks for the input, I'll be looking into this issue

**Comment by kylethornton** [comment]
thanks @dlitvakb. Please let me know if you need any further information. We are looking to build a script  and would like to use this gem.

**Comment by dlitvakb** [comment]
Hey @kylethornton,

I was able to reproduce the problem, and found a solution without having to change any code.

There are 2 possible solutions:

1) If you have multiple Spaces with different Default Locales:

Assign Default Locale per Content Type:

```ruby
your_content_type = Contentful::Management::ContentType.find('your_space', 'your_content_type')
your_content_type.client.configuration[:default_locale] = 'en-GB'

# Then operate like in the example provided
new_entry = your_content_type.entries.create(:id => 'hello-world')
new_entry.name = "Hello World"
new_entry.locale = 'en-GB'
new_entry.value_with_locales = {'en-GB'=>{"1"=>"2"}, 'es-ES'=>{"3":"4"}}
res = new_entry.save
```

> Note: If this is the case, make sure to avoid making this threaded, as the `Contentful::Management::Client` instance is shared (you can though change the instance, if you want to do so)

2) If all your Spaces share the same Default Locale

Create the `Contentful::Management::Client` with the Default Locale

```ruby
Contentful::Management::Client.new('<ACCESS_TOKEN>', default_locale: 'en-GB')
```

Please let me know if this solved your problem

**Comment by kylethornton** [comment]
Thank you @dlitvakb, I am able to get this working now.
