### ISSUE TITLE
Unable to set proxy server for callouts

### ISSUE THREAD

**Issue by kylethornton** [contentful/contentful-management.rb#88]
When using the management gem I see no way to set a proxy server. I do see the http gem is being used. Can you add support to configure callouts using a proxy server? Documentation for using a proxy server with the http gem is here:

https://github.com/httprb/http/wiki/Proxy-Support

If I can find some time I may be able to submit a pull requests.

**Comment by dlitvakb** [comment]
Hey @kylethornton,

Thanks for the suggestion, we already have this available for our CDA SDK, I'll look into adding it here as well.

Cheers

**Comment by kylethornton** [comment]
Thanks @dlitvakb I have already made use of it in the CDA SDK but have some developers struggling do develop on the CMA SDK so this would be a welcome update.

**Comment by dlitvakb** [comment]
No problem!

We're looking forward to adding this, but there's so much cool stuff going on! :smile: 

I'll try to get it done as soon as possible.

Cheers
